### ISSUE TITLE
Tower stats label change.

### ISSUE THREAD

**Issue by liyifeng94** [liyifeng94/Labyrinth-of-Polygons#101]
Split the current label into 2 parts, the label itself and the numbers into 2 separate UI texts (take a look at the other info texts in the level)

Name changes,
CurHP -> HP
ASPB -> ASpd   , is this you the attack speed?
UCost -> Upg
RCost -> Rpr , we might need something else
SGain -> Value
BCost -> Cost

**Comment by y785wang** [comment]
Done
