### ISSUE TITLE
initial path finding for flying enemies

### ISSUE THREAD

**Issue by biiuug** [liyifeng94/Labyrinth-of-Polygons#26]

**Comment by Rick-Xia** [comment]
added a new method in pathfinding.cs called SearchFlying, please call it after all obstacles have been generated, and flying enemies should call this to get the path

**Comment by biiuug** [comment]
@liyifeng94 need to include SearchFlying method in GameBoard

**Comment by liyifeng94** [comment]
Called in gameboard when the grid system is created. Need to verify.
