### ISSUE TITLE
game inilization errors on android

### ISSUE THREAD

**Issue by Rick-Xia** [liyifeng94/Labyrinth-of-Polygons#42]
[log_1.txt](https://github.com/liyifeng94/Labyrinth-of-Polygons/files/832913/log_1.txt)
[log_2.txt](https://github.com/liyifeng94/Labyrinth-of-Polygons/files/832914/log_2.txt)

the log_1.txt contains debug info generated before the game enters gameLevel
the log_2.txt contains errors after the Start button is clicked

**Comment by liyifeng94** [comment]
Fixed.
