### ISSUE TITLE
EnemyController bug.

### ISSUE THREAD

**Issue by liyifeng94** [liyifeng94/Labyrinth-of-Polygons#62]
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[UnityEngine.GameObject].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
EnemyController.SpawnEnemy () (at Assets/Scripts/EnemyController.cs:40)
EnemyController.Update () (at Assets/Scripts/EnemyController.cs:96)

**Comment by biiuug** [comment]
fixed
