### ISSUE TITLE
Dynamic tower stats. 

### ISSUE THREAD

**Issue by liyifeng94** [liyifeng94/Labyrinth-of-Polygons#73]
Need dynamic tower stats.
You can start with dynamic costs.
For example,
upgrade cost = current cost * 1.5
current cost = new upgrade cost
repair cost = (hp total - hp left) * 2
sell cost = current cost * 0.2

gold tower:
gold per wave  = current cost * 0.4

**Comment by y785wang** [comment]
What my dynamic implementaion is:
    For initialization: 
        BaseBuildCost = 1
        BaseUpgradeCost = 0.8
        BaseSellGain = 0.6
        BaseRepairCost = 0.4
    For upgrading:
        UpgradeCost = BaseUpgradeCost * CurrentLevel;
        UpgradeCost  = BaseUpgradeCost * CurrentLevel;
        SellGain = BaseSellGain * CurrentLevel;
        RepairCost = BaseRepairCost * CurrentLevel;
